### ISSUE TITLE
Project Outline  - General

### ISSUE THREAD

**Issue by r-spell** [MelissaPabst/liftoff-assignments#1]
This is so cute and great and well-sized and I love it!

You have "CRUD: Users will be able to create an order (but not an ingredient), add ingredients to an order, read an order, update/remove ingredients from an order, and delete an order." as  a feature but it seems like there are a few CRUD features.  

The account profile, the order, the order history.

I'd try and think of which of those ones to start with (personally I'd go with the order since that is the cutest part).  

I don't know how artistic/visual you are, but I think also for some a challenge with this project would to be to remember to make some of the features work before getting carried away with the visuals.

**Comment by MelissaPabst** [comment]
Yeah, too many CRUD features to make it one "feature".
